### ISSUE TITLE
possible typo?

### ISSUE THREAD

**Issue by tomaszkomin** [lukeb2014/Dropbox-PHP-SDK-v2#10]
I think in Dropbox/Files.php line 342
fwrite($file, $data); // throws variable $data is unused in that scope for me  
should be changed to:
fwrite($file, $returnData);

regards 
Tomasz Komin

**Comment by lukeb2014** [comment]
Yes, that is a typo, thank you.

Please let me know if https://github.com/lukeb2014/Dropbox-v2-PHP-SDK/commit/9c6e7fdce05478611d91c1394d4e7e93a81d1084 fixes the issue.

Luke

**Comment by tomaszkomin** [comment]
Yes that works for me:)


W dniu piątek, 8 lutego 2019 Luke Baird <notifications@github.com>
napisał(a):
