### ISSUE TITLE
Dropbox connection error

### ISSUE THREAD

**Issue by asimakos** [lukeb2014/Dropbox-PHP-SDK-v2#3]
Congrats for your dropbox-php-sdk!

I followed all your instructions to install successfully this API via composer. I try to connect to my Dropbox account via access_token as clearly mentioned in your Example.php but i get the following error:
![dropbox](https://user-images.githubusercontent.com/15226087/35927444-641fbd04-0c33-11e8-8e5b-1c7c3014ed7b.jpg)
Any kind of help as i use [Wampserver 2.5](https://sourceforge.net/projects/wampserver/files/WampServer%202/Wampserver%202.5/)? Could you add some extra code to your Example.php as there is no wiki section?

Regards

**Comment by lukeb2014** [comment]
`list` is a reserved PHP function, hence why the error is being generated. I renamed this `listf` and will be releasing an update with this fix today.

**Comment by lukeb2014** [comment]
Released fix, please let me know if your issue is fixed.

**Comment by asimakos** [comment]
Thanks for your reply! Unfortunately i have got the same error but in different file now. I think it would be wiser to check it firstly using a dropbox account, before uploading anything to github.

![dropbox](https://user-images.githubusercontent.com/15226087/35973432-1589862e-0cde-11e8-8281-6b57419a5bfa.jpg)

Regards

**Comment by asimakos** [comment]
I tried one more time today and I got the same error! Should I expect something soon as well as extending your example.php file as clearly mentioned?

I have to admit that I tried before some other drop box php sdk in github via composer and I have got similar errors or even worse composer installation errors. I would be very happy to find something bug free.

Regards

**Comment by lukeb2014** [comment]
I will be working on this issue over the weekend. I'll keep you updated, I
cleaned up this bug but found another.

**Comment by lukeb2014** [comment]
I have `Example.php` working on my end. The "bug" I was having on my end was an SSL certificate issue:

https://stackoverflow.com/questions/28858351/php-ssl-certificate-error-unable-to-get-local-issuer-certificate

Let me know if you're able to get this working now. Thank you for alerting me to this.

**Comment by asimakos** [comment]
Unfortunately i have got the same error! Regarding your SSL certificate solution, i managed to run successfully the following [dropbox-php-sdk ](https://github.com/kunalvarma05/dropbox-php-sdk) without errors especially the part fetching file information from a dropbox account. I hope not to have got problems afterwards with uploading, download, etc.
Many dropbox-php-sdk don't work unfortunately in github, but i am not aware of this SSL certificate to run successfully even for localhost development!

Regards

**Comment by lukeb2014** [comment]
Did you remember to run `composer update` before re-testing the SDK?

I'm glad the StackOverflow article helped at least. I'll add that to the
README at the bottom.

**Comment by asimakos** [comment]
I will definitely check it and will let you know what is the best for me between these two sdks. Which of them uses the least code from my side. I checked too many dropbox packages unsuccessfully and I may forgot to use it. 

Regards

**Comment by lukeb2014** [comment]
Closing https://github.com/lukeb2014/Dropbox-v2-PHP-SDK/issues/3
